# config.yaml

learning_rate: 0.01
batch_size: 64
n_epochs: 2000

eval_injections_file: /home/phutane/instadeep/validation/injections.npy
eval_adjacency_file: /home/phutane/instadeep/validation/adjacency.json
